services:
    reservations:
        build:
            context: .
            dockerfile: ./apps/reservations-api/Dockerfile
            target: development
        command: npx nx run reservations-api:serve
        env_file:
            - ./apps/reservations-api/.env
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules

    authentication:
        build:
            context: .
            dockerfile: ./apps/authentication-api/Dockerfile
            target: development
        command: npx nx run authentication-api:serve
        env_file:
            - ./apps/authentication-api/.env
        ports:
            - '3001:3001'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
    # mongo:
    #     image: mongo
